/**
 * Realistic mock dataset matching the PostgreSQL / Prisma database schema
 * and API Contract specifications.
 */

export const mockUser = {
  id: 1,
  name: 'Aarohi Sharma',
  firstName: 'Aarohi',
  lastName: 'Sharma',
  fullName: 'Aarohi Sharma',
  email: 'aarohi.sharma@example.com',
  phoneNumber: '+91 9876543210',
  city: 'Mumbai',
  country: 'India',
  bio: 'Passionate travel blogger exploring hidden gems, architecture, and local culinary adventures around the world.',
  role: 'USER',
  profileImageUrl: '', // Empty triggers the avatar circle with initial / name fallback like in screenshot
  stats: {
    tripsPlanned: 12,
    placesExplored: 18,
    photosCaptured: 234,
    countriesVisited: 6,
  },
  preference: {
    language: 'en',
    preferredCurrency: 'USD',
    budgetLevel: 'MEDIUM',
    travelStyle: 'ADVENTUROUS',
  },
};

export const mockPreplannedTrips = [
  {
    id: 101,
    name: 'Maldives Getaway',
    destination: 'Maldives',
    locationSummary: 'Maldives',
    description: 'Luxury overwater bungalow retreat with turquoise lagoon snorkeling and private island sunset cruises.',
    startDate: '2024-05-20T00:00:00.000Z',
    endDate: '2024-05-27T00:00:00.000Z',
    formattedDates: 'May 20 - May 27, 2024',
    badge: 'In 12 days',
    badgeVariant: 'warning',
    travelerCount: 2,
    budget: 3500,
    currency: 'USD',
    coverImageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
    stops: [
      { id: 1, cityName: 'Malé', countryName: 'Maldives', order: 1 },
      { id: 2, cityName: 'Baa Atoll', countryName: 'Maldives', order: 2 },
    ],
  },
  {
    id: 102,
    name: 'Swiss Adventure',
    destination: 'Switzerland',
    locationSummary: 'Switzerland',
    description: 'Alpine wonderland exploration across Zermatt, Interlaken lakes, and scenic Glacier Express railways.',
    startDate: '2024-06-15T00:00:00.000Z',
    endDate: '2024-06-22T00:00:00.000Z',
    formattedDates: 'Jun 15 - Jun 22, 2024',
    badge: 'In 1 month',
    badgeVariant: 'success',
    travelerCount: 2,
    budget: 4200,
    currency: 'USD',
    coverImageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80',
    stops: [
      { id: 3, cityName: 'Interlaken', countryName: 'Switzerland', order: 1 },
      { id: 4, cityName: 'Zermatt', countryName: 'Switzerland', order: 2 },
    ],
  },
  {
    id: 103,
    name: 'Japan Tour',
    destination: 'Tokyo, Kyoto, Osaka',
    locationSummary: 'Tokyo, Kyoto, Osaka',
    description: 'Cultural expedition spanning Shinjuku nightlife, historic Gion geisha districts, and Dotonbori culinary alleys.',
    startDate: '2024-08-10T00:00:00.000Z',
    endDate: '2024-08-20T00:00:00.000Z',
    formattedDates: 'Aug 10 - Aug 20, 2024',
    badge: 'In 2 months',
    badgeVariant: 'success',
    travelerCount: 2,
    budget: 3900,
    currency: 'USD',
    coverImageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    stops: [
      { id: 5, cityName: 'Tokyo', countryName: 'Japan', order: 1 },
      { id: 6, cityName: 'Kyoto', countryName: 'Japan', order: 2 },
      { id: 7, cityName: 'Osaka', countryName: 'Japan', order: 3 },
    ],
  },
];

export const mockPreviousTrips = [
  {
    id: 201,
    name: 'Greek Island Escape',
    destination: 'Santorini, Greece',
    locationSummary: 'Santorini, Greece',
    description: 'White-washed cliffside villages, stunning Oia sunsets, and relaxing catamaran excursions across the Aegean.',
    startDate: '2024-04-10T00:00:00.000Z',
    endDate: '2024-04-18T00:00:00.000Z',
    formattedDates: 'Apr 10 - Apr 18, 2024',
    badge: 'Completed',
    badgeVariant: 'completed',
    travelerCount: 2,
    budget: 2800,
    currency: 'USD',
    coverImageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80',
    stops: [
      { id: 8, cityName: 'Santorini', countryName: 'Greece', order: 1 },
      { id: 9, cityName: 'Mykonos', countryName: 'Greece', order: 2 },
    ],
  },
  {
    id: 202,
    name: 'Turkey Explorer',
    destination: 'Istanbul, Cappadocia',
    locationSummary: 'Istanbul, Cappadocia',
    description: 'Sunrise hot air ballooning over fairy chimneys and discovering Hagia Sophia and spice bazaars in Istanbul.',
    startDate: '2024-02-05T00:00:00.000Z',
    endDate: '2024-02-13T00:00:00.000Z',
    formattedDates: 'Feb 5 - Feb 13, 2024',
    badge: 'Completed',
    badgeVariant: 'completed',
    travelerCount: 2,
    budget: 2200,
    currency: 'USD',
    coverImageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=800&q=80',
    stops: [
      { id: 10, cityName: 'Istanbul', countryName: 'Turkey', order: 1 },
      { id: 11, cityName: 'Cappadocia', countryName: 'Turkey', order: 2 },
    ],
  },
  {
    id: 203,
    name: 'Dubai Experience',
    destination: 'Dubai, UAE',
    locationSummary: 'Dubai, UAE',
    description: 'Dazzling architectural wonders, desert dune-bashing safaris, and waterfront luxury dining in downtown Dubai.',
    startDate: '2023-12-20T00:00:00.000Z',
    endDate: '2023-12-27T00:00:00.000Z',
    formattedDates: 'Dec 20 - Dec 27, 2023',
    badge: 'Completed',
    badgeVariant: 'completed',
    travelerCount: 2,
    budget: 3100,
    currency: 'USD',
    coverImageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    stops: [
      { id: 12, cityName: 'Dubai', countryName: 'UAE', order: 1 },
    ],
  },
];

export const mockRegions = [
  {
    id: 'europe',
    name: 'Europe',
    destinationCount: 50,
    destinationCountLabel: '50+ Destinations',
    coverImageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    description: 'Iconic historic landmarks, diverse cultures, and world-class gastronomy.',
    popularCities: ['Paris', 'Rome', 'Santorini', 'Athens', 'Venice'],
  },
  {
    id: 'asia',
    name: 'Asia',
    destinationCount: 60,
    destinationCountLabel: '60+ Destinations',
    coverImageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    description: 'Ancient heritage temples, vibrant night markets, and futuristic skylines.',
    popularCities: ['Tokyo', 'Kyoto', 'Malé', 'Mumbai', 'Jaipur'],
  },
  {
    id: 'north-america',
    name: 'North America',
    destinationCount: 40,
    destinationCountLabel: '40+ Destinations',
    coverImageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    description: 'Majestic national parks, coastal highways, and buzzing cosmopolitan hubs.',
    popularCities: ['New York City', 'San Francisco', 'Vancouver', 'Mexico City', 'Los Angeles'],
  },
  {
    id: 'south-america',
    name: 'South America',
    destinationCount: 30,
    destinationCountLabel: '30+ Destinations',
    coverImageUrl: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=800&q=80',
    description: 'Amazon rainforest wonders, Andean mountain passes, and lively carnival spirit.',
    popularCities: ['Cusco', 'Rio de Janeiro', 'Buenos Aires', 'Lima', 'Santiago'],
  },
  {
    id: 'africa',
    name: 'Africa',
    destinationCount: 25,
    destinationCountLabel: '25+ Destinations',
    coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    description: 'Breathtaking savannah safaris, Sahara dunes, and rich cultural tapestries.',
    popularCities: ['Cairo', 'Cape Town', 'Marrakech', 'Nairobi', 'Zanzibar'],
  },
];

export const mockTrips = [...mockPreplannedTrips, ...mockPreviousTrips];
